### PR TITLE
Fix creation of conditions

### LINKED ISSUE #1053: Impossible de créer des champs conditionnels
Bonjour,

**Describe the bug**
Lorsque j'essaie d'ajouter une condition dans un formulaire, la liste de la condition est vide (voir screenshot) alors que jusqu'à hier cela fonctionnait.
J'ai bien d'autres champs dans mon formulaire.

**Screenshots**
image

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser : Chrome

Avez vous une idée ?

Merci

### PR DESCRIPTION
**Pull request by btry**
fix question condition creation.

### CODE REVIEW

File: ajax/question_condition.php [hunk 1]
```diff
@@ -32,24 +32,16 @@
...
    exit;
 }
-$questionId = (int) $_REQUEST['plugin_formcreator_questions_id'];
-if ($questionId == 0) {
-   $formId = (int) $_REQUEST['plugin_formcreator_forms_id'];
-} else {
-   $form = new PluginFormcreatorForm();
-   $form->getByQuestionId($questionId);
-   $formId = $form->getID();
-}
```
Comment (btry) [inline ajax/question_condition.php]: $_REQUEST['plugin_formcreator_questions_id'] is always set when calling this entry point
