### PR TITLE
Deleting ticket does not delete associated issue

### LINKED ISSUE #2918: The "Put in trash bin" button is not working
**Describe the bug**
The "Put in trash bin" button is not working. When the self-service profile user clicks this button, no action is taken on the ticket and nothing different appears in the log either.

**To Reproduce**
1. Access a ticket with a self-service profile user;
2. Click on "Put in trash bin" button;
3. The screen refreshes, but the ticket does not change

**Expected behavior**
The ticket should have the status changed or cancelled.

**Screenshots**
image

**GLPI / Plugins (please complete the following information):**
<details><summary>Instruções de instalação e configuração</summary><pre>GLPI 10.0.2 (/glpi => C:\xampp\htdocs\glpi)
Installation mode: TARBALL
Current language:pt_BR

</details><details><summary>Server</summary><pre> 
Operating system: Windows NT UNOUNIV-VFNBAD8 10.0 build 19044 (Windows 10) AMD64
PHP 8.1.6 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, bcmath, bz2, calendar,
	ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, intl, json, ldap, libxml, mbstring, mysqli,
	mysqlnd, openssl, pcre, pdo_mysql, pdo_sqlite, readline, session, standard, tokenizer, xml, xmlreader, xmlwriter, zip, zlib)
Setup: max_execution_time="120" memory_limit="1024M" post_max_size="40M" safe_mode="" session.save_handler="files"
	upload_max_filesize="40M" 
Software: Apache/2.4.53 (Win64) OpenSSL/1.1.1n PHP/8.1.6 (Apache/2.4.53 (Win64) OpenSSL/1.1.1n PHP/8.1.6 Server at localhost
	Port 80
)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:103.0) Gecko/20100101 Firefox/103.0
Server Software: mariadb.org binary distribution
	Server Version: 10.4.24-MariaDB
	Server SQL Mode: NO_ZERO_IN_DATE,NO_ZERO_DATE,NO_ENGINE_SUBSTITUTION
	Parameters: root@localhost/glpidb
	Host info: localhost via TCP/IP
	
PHP version (8.1.6) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.
gd extension is installed.
intl extension is installed.
libxml extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.4.24) is supported.
The log file has been created successfully.
Write access to C:\xampp\htdocs\glpi/files/_cache has been validated.
Write access to C:\xampp\htdocs\glpi/config has been validated.
Write access to C:\xampp\htdocs\glpi/files/_cron has been validated.
Write access to C:\xampp\htdocs\glpi/files has been validated.
Write access to C:\xampp\htdocs\glpi/files/_dumps has been validated.
Write access to C:\xampp\htdocs\glpi/files/_graphs has been validated.
Write access to C:\xampp\htdocs\glpi/files/_lock has been validated.
Write access to C:\xampp\htdocs\glpi/files/_pictures has been validated.
Write access to C:\xampp\htdocs\glpi/files/_plugins has been validated.
Write access to C:\xampp\htdocs\glpi/files/_rss has been validated.
Write access to C:\xampp\htdocs\glpi/files/_sessions has been validated.
Write access to C:\xampp\htdocs\glpi/files/_tmp has been validated.
Write access to C:\xampp\htdocs\glpi/files/_uploads has been validated.
Web access to files directory is protected
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
zip extension is installed.
bz2 extension is installed.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring.
Following extensions are not present: sodium.
Write access to C:\xampp\htdocs\glpi/marketplace has been validated.
Timezones seems not loaded, see https://glpi-install.readthedocs.io/en/latest/timezones.html.

</details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: C:\xampp\htdocs\glpi
GLPI_CONFIG_DIR: C:\xampp\htdocs\glpi/config
GLPI_VAR_DIR: C:\xampp\htdocs\glpi/files
GLPI_MARKETPLACE_DIR: C:\xampp\htdocs\glpi/marketplace
GLPI_USE_CSRF_CHECK: 1
GLPI_CSRF_EXPIRES: 7200
GLPI_CSRF_MAX_TOKENS: 100
GLPI_USE_IDOR_CHECK: 1
GLPI_IDOR_EXPIRES: 7200
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: 
GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org
GLPI_INSTALL_MODE: TARBALL
GLPI_NETWORK_MAIL: glpi@teclib.com
GLPI_NETWORK_SERVICES: https://services.glpi-network.com
GLPI_MARKETPLACE_ALLOW_OVERRIDE: 1
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: 1
GLPI_USER_AGENT_EXTRA_COMMENTS: 
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: 1
GLPI_AJAX_DASHBOARD: 1
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: 0
GLPI_CENTRAL_WARNINGS: 1
GLPI_DOC_DIR: C:\xampp\htdocs\glpi/files
GLPI_CACHE_DIR: C:\xampp\htdocs\glpi/files/_cache
GLPI_CRON_DIR: C:\xampp\htdocs\glpi/files/_cron
GLPI_DUMP_DIR: C:\xampp\htdocs\glpi/files/_dumps
GLPI_GRAPH_DIR: C:\xampp\htdocs\glpi/files/_graphs
GLPI_LOCAL_I18N_DIR: C:\xampp\htdocs\glpi/files/_locales
GLPI_LOCK_DIR: C:\xampp\htdocs\glpi/files/_lock
GLPI_LOG_DIR: C:\xampp\htdocs\glpi/files/_log
GLPI_PICTURE_DIR: C:\xampp\htdocs\glpi/files/_pictures
GLPI_PLUGIN_DOC_DIR: C:\xampp\htdocs\glpi/files/_plugins
GLPI_RSS_DIR: C:\xampp\htdocs\glpi/files/_rss
GLPI_SESSION_DIR: C:\xampp\htdocs\glpi/files/_sessions
GLPI_TMP_DIR: C:\xampp\htdocs\glpi/files/_tmp
GLPI_UPLOAD_DIR: C:\xampp\htdocs\glpi/files/_uploads
GLPI_INVENTORY_DIR: C:\xampp\htdocs\glpi/files/_inventories
GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/
GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/
GLPI_I18N_DIR: C:\xampp\htdocs\glpi/locales
GLPI_VERSION: 10.0.2
GLPI_SCHEMA_VERSION: 10.0.2@a130db99c7d9b131c2e2ea59fe0d6260fe93d831
GLPI_MARKETPLACE_PRERELEASES: 
GLPI_MIN_PHP: 7.4.0
GLPI_MAX_PHP: 8.2.0
GLPI_YEAR: 2022

</details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.6 in (C:\xampp\htdocs\glpi\vendor\htmlawed\htmlawed)
phpmailer/phpmailer version 6.6.0 in (C:\xampp\htdocs\glpi\vendor\phpmailer\phpmailer\src)
simplepie/simplepie version 1.5.8 in (C:\xampp\htdocs\glpi\vendor\simplepie\simplepie\library)
tecnickcom/tcpdf version 6.4.4 in (C:\xampp\htdocs\glpi\vendor\tecnickcom\tcpdf)
michelf/php-markdown in (C:\xampp\htdocs\glpi\vendor\michelf\php-markdown\Michelf)
true/punycode in (C:\xampp\htdocs\glpi\vendor\true\punycode\src)
iamcal/lib_autolink in (C:\xampp\htdocs\glpi\vendor\iamcal\lib_autolink)
sabre/dav in (C:\xampp\htdocs\glpi\vendor\sabre\dav\lib\DAV)
sabre/http in (C:\xampp\htdocs\glpi\vendor\sabre\http\lib)
sabre/uri in (C:\xampp\htdocs\glpi\vendor\sabre\uri\lib)
sabre/vobject in (C:\xampp\htdocs\glpi\vendor\sabre\vobject\lib)
laminas/laminas-i18n in (C:\xampp\htdocs\glpi\vendor\laminas\laminas-i18n\src)
laminas/laminas-servicemanager in (C:\xampp\htdocs\glpi\vendor\laminas\laminas-servicemanager\src)
monolog/monolog in (C:\xampp\htdocs\glpi\vendor\monolog\monolog\src\Monolog)
sebastian/diff in (C:\xampp\htdocs\glpi\vendor\sebastian\diff\src)
donatj/phpuseragentparser in (C:\xampp\htdocs\glpi\vendor\donatj\phpuseragentparser\src\UserAgent)
elvanto/litemoji in (C:\xampp\htdocs\glpi\vendor\elvanto\litemoji\src)
symfony/console in (C:\xampp\htdocs\glpi\vendor\symfony\console)
scssphp/scssphp in (C:\xampp\htdocs\glpi\vendor\scssphp\scssphp\src)
laminas/laminas-mail in (C:\xampp\htdocs\glpi\vendor\laminas\laminas-mail\src\Protocol)
laminas/laminas-mime in (C:\xampp\htdocs\glpi\vendor\laminas\laminas-mime\src)
rlanvin/php-rrule in (C:\xampp\htdocs\glpi\vendor\rlanvin\php-rrule\src)
blueimp/jquery-file-upload in (C:\xampp\htdocs\glpi\vendor\blueimp\jquery-file-upload\server\php)
ramsey/uuid in (C:\xampp\htdocs\glpi\vendor\ramsey\uuid\src)
psr/log in (C:\xampp\htdocs\glpi\vendor\psr\log\Psr\Log)
psr/simple-cache in (C:\xampp\htdocs\glpi\vendor\psr\simple-cache\src)
psr/cache in (C:\xampp\htdocs\glpi\vendor\psr\cache\src)
league/csv in (C:\xampp\htdocs\glpi\vendor\league\csv\src)
mexitek/phpcolors in (C:\xampp\htdocs\glpi\vendor\mexitek\phpcolors\src\Mexitek\PHPColors)
guzzlehttp/guzzle in (C:\xampp\htdocs\glpi\vendor\guzzlehttp\guzzle\src)
guzzlehttp/psr7 in (C:\xampp\htdocs\glpi\vendor\guzzlehttp\psr7\src)
glpi-project/inventory_format in (C:\xampp\htdocs\glpi\vendor\glpi-project\inventory_format\lib\php)
wapmorgan/unified-archive in (C:\xampp\htdocs\glpi\vendor\wapmorgan\unified-archive\src)
paragonie/sodium_compat in (C:\xampp\htdocs\glpi\vendor\paragonie\sodium_compat\src)
symfony/cache in (C:\xampp\htdocs\glpi\vendor\symfony\cache)
html2text/html2text in (C:\xampp\htdocs\glpi\vendor\html2text\html2text\src)
symfony/css-selector in (C:\xampp\htdocs\glpi\vendor\symfony\css-selector)
symfony/dom-crawler in (C:\xampp\htdocs\glpi\vendor\symfony\dom-crawler)
twig/twig in (C:\xampp\htdocs\glpi\vendor\twig\twig\src)
twig/string-extra in (C:\xampp\htdocs\glpi\vendor\twig\string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 not found
symfony/polyfill-php81 not found

</details><details><summary>LDAP directories</summary><pre> 
Server: '10.200.3.1', Port: '389', BaseDN: 'ou=people,dc=ufpr,dc=br', Connection filter: none, RootDN: none, Use TLS: none

</details><details><summary>SQL replicas</summary><pre> 
Not active

</details><details><summary>Notifications</summary><pre> 
Way of sending emails: PHP

</details><details><summary>Plugins list</summary><pre> 
	fields               Name: Additional fields              Version: 1.17.0     State: Enabled                                 
		Install Method: Manual
	behaviors            Name: Comportamentos                 Version: 2.7.2      State: Enabled                                 
		Install Method: Manual
	datainjection        Name: Data injection                 Version: 2.11.2     State: Installed / not activated               
		Install Method: Manual
	escalade             Name: Escalation                     Version: 2.8.0      State: Enabled                                 
		Install Method: Manual
	formcreator          Name: Form Creator                   Version: 2.13.0-rc.2 State: Enabled                                 
		Install Method: Manual
	genericobject        Name: Gerenciamento de objetos       Version: 2.12.1     State: Enabled                                 
		Install Method: Manual
	itilcategorygroups   Name: Grupos ItilCategory            Version: 2.5.0      State: Enabled                                 
		Install Method: Manual
	tag                  Name: Tag Management                 Version: 2.9.2      State: Installed / not activated               
		Install Method: Manual

</pre></details>

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome, Versão 104.0.5112.81 (Versão oficial) 64 bits

**Additional context**

The "cancel" button on that same screen is also not working.

I also opened an issue about the problem with the cancel button.

The issue is in the link below:

https://github.com/pluginsGLPI/formcreator/issues/2911

### PR DESCRIPTION
**Pull request by btry**
fix #2918

### CODE REVIEW

File: hook.php [hunk 1]
```diff
@@ -438,17 +433,7 @@ function plugin_formcreator_hook_update_ticket(CommonDBTM $item) {
...
-         'SELECT' => 'items_id',
-         'FROM'   => Item_Ticket::getTable(),
-         'WHERE'  => [
-            'itemtype' => PluginFormcreatorFormAnswer::getType(),
-            'tickets_id' => $id,
-         ]
-      ])
-   ]);
-   if ($formAnswer->isNewItem()) {
+   if ($formAnswer->getFromDbByTicket($id)) {
```
Comment (btry) [inline hook.php:436]: code factorization

Comment (btry) [inline hook.php:436]: code factorization

File: hook.php [hunk 2]
```diff
@@ -469,30 +454,19 @@ function plugin_formcreator_hook_delete_ticket(CommonDBTM $item) {
...
-         'SELECT' => 'items_id',
-         'FROM'   => Item_Ticket::getTable(),
-         'WHERE'  => [
-            'itemtype' => PluginFormcreatorFormAnswer::getType(),
-            'tickets_id' => $id,
-         ]
-      ])
-   ]);
-   if (!$formAnswer->isNewItem()) {
+   if ($formAnswer->getFromDbByTicket($id)) {
```
Comment (btry) [inline hook.php:459]: code factorization

File: hook.php [hunk 3]
```diff
@@ -344,11 +344,6 @@ function plugin_formcreator_hook_add_ticket(CommonDBTM $item) {
       return;
    }
 
-   if (isset($item->input['items_id'][PluginFormcreatorFormAnswer::getType()])) {
-      // the ticket is associated to a form answer
-      return;
-   }
```
Comment (btry) [inline hook.php:350]: When the execution flow reaches this point, we are sure that the ticket is not addesd by Formcreator, then the ticket is not from a group of tickets genearated by a formanswer object. This early end of function causes inconsistencies.

File: hook.php [hunk 4]
```diff
@@ -469,30 +454,19 @@ function plugin_formcreator_hook_delete_ticket(CommonDBTM $item) {
...
-   if (!$formAnswer->isNewItem()) {
+   if ($formAnswer->getFromDbByTicket($id)) {
       $minimalStatus = $formAnswer->getAggregatedStatus();
       if ($minimalStatus === null) {
          // There is no more ticket in the form anwer
          $formAnswer->updateStatus(CommonITILObject::CLOSED);
       } else {
          $formAnswer->updateStatus($minimalStatus);
       }
-      return;
```
Comment (btry) [inline hook.php:492]: Maybe thre is only 1 ticket associated to a the form answer. In such case, we must also delete the issue which represents the ticket. See PluginFormcreatorFormAnswer::createIssue(). I nthis method if there is only 1 generated ticket  then we create an issue ssociated to this ticket.

File: hook.php [hunk 5]
```diff
@@ -503,25 +477,16 @@ function plugin_formcreator_hook_delete_ticket(CommonDBTM $item) {
...
-   $formAnswer->getFromDBByCrit([
-      'id' => new QuerySubQuery([
-         'SELECT' => 'items_id',
-         'FROM'   => Item_Ticket::getTable(),
-         'WHERE'  => [
-            'itemtype' => PluginFormcreatorFormAnswer::getType(),
-            'tickets_id' => $item->getID(),
-         ]
-      ])
-   ]);
```
Comment (btry) [inline hook.php:515]: code factorization

File: hook.php [hunk 6]
```diff
@@ -503,25 +477,16 @@ function plugin_formcreator_hook_delete_ticket(CommonDBTM $item) {
...
-   if ($formAnswer->isNewItem()) {
-      plugin_formcreator_hook_add_ticket($item);
+   if ($formAnswer->getFromDbByTicket($item)) {
+      $formAnswer->createIssue();
+      $minimalStatus = $formAnswer->getAggregatedStatus();
+      if ($minimalStatus !== null) {
+         $formAnswer->updateStatus($minimalStatus);
+      }
       return;
    }
```
Comment (btry) [inline hook.php:487]: if statement inverted

when there is a form answer associated to the ticket then the status of the form answer must be updated by the ticket restoratin event because several tickets may be ssociated to this form answer instance.

If there is no form answer associated to the ticket, then a new issue must be recreated from the restored ticket.

File: hook.php [hunk 7]
```diff
@@ -531,27 +496,16 @@ function plugin_formcreator_hook_purge_ticket(CommonDBTM $item) {
...
-   $formAnswer->getFromDBByCrit([
-      'id' => new QuerySubQuery([
-         'SELECT' => 'items_id',
-         'FROM'   => Item_Ticket::getTable(),
-         'WHERE'  => [
-            'itemtype' => PluginFormcreatorFormAnswer::getType(),
-            'tickets_id' => $id,
-         ]
-      ])
-   ]);
```
Comment (btry) [inline hook.php:545]: code factorization

File: hook.php [hunk 8]
```diff
@@ -531,27 +496,16 @@ function plugin_formcreator_hook_purge_ticket(CommonDBTM $item) {
...
-   if (!$formAnswer->isNewItem()) {
+   if ($formAnswer->getFromDbByTicket($id)) {
```
Comment (btry) [inline hook.php:501]: if inverted

if a form answer is associated to the ticket being purged then the status if this fom answer must e updated.

File: hook.php [hunk 9]
```diff
@@ -531,27 +496,16 @@ function plugin_formcreator_hook_purge_ticket(CommonDBTM $item) {
...
       $minimalStatus = $formAnswer->getAggregatedStatus();
       if ($minimalStatus === null) {
          // There is no more ticket in the form anwer
          $formAnswer->updateStatus(CommonITILObject::CLOSED);
       } else {
          $formAnswer->updateStatus($minimalStatus);
       }
-      return;
```
Comment (btry) [inline hook.php:554]: after updatiing the form answer, we must delete the issue which represents tie ticket, if any (this happens when there is only 1 ticket associated to the form answer)

File: inc/formanswer.class.php [hunk 10]
```diff
@@ -1345,14 +1347,9 @@ private function sendNotification() {
       }
    }
 
-   private function createIssue() {
+   public function createIssue() {
```
Comment (btry) [inline inc/formanswer.class.php:1350]: the method may be called from a hook

File: inc/formanswer.class.php [hunk 11]
```diff
@@ -1099,7 +1099,9 @@ public function post_addItem() {
             return;
          }
       }
-      $this->createIssue();
+      if ($this->input['status'] != self::STATUS_REFUSED) {
+         $this->createIssue();
+      }
```
Comment (btry) [inline inc/formanswer.class.php:1104]: if statement moved outside the createIssue() method

File: setup.php [hunk 12]
```diff
@@ -488,6 +488,21 @@ function plugin_formcreator_redirect() {
...
+   ];
+   foreach ($pages as $srcPage => $dstPage) {
+      if (strpos($_SERVER['REQUEST_URI'], $srcPage) !== false && strpos($_SERVER['REQUEST_URI'], $dstPage) === false) {
+         if ($srcPage == 'front/reservationitem.php') {
+            $_SESSION['plugin_formcreator']['redirected']['POST'] = $_POST;
+         }
+         Html::redirect($dstPage);
+         break;
+      }
+   }
```
Comment (btry) [inline setup.php:505]: restore missing rediretions which existed in 2.12 versions
