### PR TITLE
fix(ui): require JS tinymce when displaying target ticket and rich text is enabled

### LINKED ISSUE #754: Destination: specific entity [9.2]
No additional dropdown is loaded, using GLPI 9.2 and the RC release of FormCreator. 

In the old version you would get a addtional dropdown where you could specify extra information.
I can see it not working for the specific entity but I think there's more.. the plugin is acting odd.

### PR DESCRIPTION
**Pull request by btry**
fix #754

### CODE REVIEW

File: setup.php [hunk 1]
```diff
@@ -165,6 +165,10 @@ function plugin_init_formcreator() {
             $PLUGIN_HOOKS['add_javascript']['formcreator'][] = 'js/scripts.js.php';
          }
 
+         if (strpos($_SERVER['REQUEST_URI'], "plugins/formcreator/front/targetticket.form.php") !== false) {
```
Comment (trasher) [inline setup.php]: I guess it would be better to use `$CFG_GLPI['javascript'] `
